version: "3"
services:
  web:
    image: doc-web:latest
    container_name: easydoc-web
    restart: always
    labels:
      - topsec.role=web
    build:
      context: .
      dockerfile: ./Dockerfile_topsec

    volumes:
      - /topsec/EasyDoc/config:/EasyDoc/config
      - /topsec/EasyDoc/media:/EasyDoc/media
#      - /topsec/EasyDoc/db:/EasyDoc/db
    environment:
      - TZ=Asia/Shanghai
##### 以下注释项为可选变量
      - LISTEN_PORT=80   # 自定义端口
      - CREATE_USER=1       # 0 不创建管理员用户, 1 创建管理员用户,默认是1
      - USER=topsec     # 自定义管理员用户名
      - MM=Topsec123!@#                # 自定义管理员密码
##### 如果默认用户密码,以及变量添加用户密码无法登录,请参考:https://www.mrdoc.fun/project-1/doc-242/
    ports:
      - "80:80"
    depends_on:
      - mysql

  easydoc-db:
    image: mysql:5.7
    container_name: easydoc-db
    restart: always
    labels:
      - topsec.role=db
    volumes:
      - /topsec/EasyDoc/db:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=Topsec123!@#
      - MYSQL_DATABASE=easydoc
      - MYSQL_USER=topsec
      - MYSQL_PASSWORD=Topsec123!@#
    expose:
      - "3306"
    ports:
      - "33306:3306"  # 如果不需要外部连接mysql,可注释此行+上一行.
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"


# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  easydoc-data:
    driver: local
  mysql-data:
    driver: local